# ExternalSecrets Operator Example
# This integrates with AWS Secrets Manager, Google Secret Manager, or Hashicorp Vault

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: luna-backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: luna-backend  # ServiceAccount with IRSA annotations
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: luna-backend-secrets
  namespace: luna-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: luna-backend-secrets  # Kubernetes Secret name
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: luna/backend/database  # AWS Secrets Manager secret name
        property: url  # JSON key in the secret
    
    - secretKey: redis-url
      remoteRef:
        key: luna/backend/redis
        property: url
    
    - secretKey: rabbitmq-url
      remoteRef:
        key: luna/backend/rabbitmq
        property: url
    
    - secretKey: minio-access-key
      remoteRef:
        key: luna/backend/minio
        property: access_key
    
    - secretKey: minio-secret-key
      remoteRef:
        key: luna/backend/minio
        property: secret_key
    
    - secretKey: jwt-secret-key
      remoteRef:
        key: luna/backend/jwt
        property: secret_key

---
# For AWS IRSA (IAM Roles for Service Accounts)
# Annotate the ServiceAccount in Helm values.yaml:
#
# serviceAccount:
#   create: true
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/luna-backend-secrets-role
#
# The IAM role should have permissions to access Secrets Manager:
# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#         "secretsmanager:GetSecretValue",
#         "secretsmanager:DescribeSecret"
#       ],
#       "Resource": "arn:aws:secretsmanager:us-east-1:ACCOUNT_ID:secret:luna/backend/*"
#     }
#   ]
# }
